# Generated by Django 5.0 on 2023-12-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_logo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='map_location',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
