# Generated by Django 5.0 on 2023-12-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_event_total_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='available',
            field=models.BooleanField(null=True),
        ),
    ]
