# Generated by Django 5.0 on 2024-01-17 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_ticket_available'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
