# Generated by Django 5.0 on 2024-01-17 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_delete_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=10)),
                ('seat_number', models.CharField(max_length=10)),
                ('available', models.CharField(max_length=20, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.event')),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
    ]
