# Generated by Django 5.0 on 2024-01-17 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_ticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCard',
        ),
    ]
