# Generated by Django 5.0 on 2024-01-17 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_usercard_expire_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercard',
            old_name='expire_date',
            new_name='expiry_date',
        ),
    ]
